### ISSUE TITLE
Nuget .Net Core Version?

### ISSUE THREAD

**Issue by MikeBairdRocks** [rebus-org/Rebus.MsgPack#1]
Looks like the project could/should support .NetStandard. Also, what do you think about using [MessagePack-CSharp](https://github.com/neuecc/MessagePack-CSharp)? I created a serializer using it and it works well. I can submit a PR if you would like with the requested changes.

**Comment by mookid8000** [comment]
Cool, that would be neat 😄

**Comment by mookid8000** [comment]
Hi there @MikeBairdRocks , so how is it going?
