### ISSUE TITLE
.NET Standard Support

### ISSUE THREAD

**Issue by RoyDFRISS** [rebus-org/Rebus.MsgPack#3]
For the nuget package

**Comment by mookid8000** [comment]
Rebus.MsgPack 5.0.0 targets .NET Standard 2.0 and is updated to MessagePack 1.9.11

**Comment by mookid8000** [comment]
for Bingability's sake, I also want to mention here: I just released Rebus.MsgPack 6.0.0, which is upgraded to Rebus 6 and MessagePack 2.1.90
